version: '3.8'

services:
  frontend:
    image: gtombrink/oaem-web:latest

  backend:
    image: gtombrink/oaem-api:latest

  reverse-proxy:
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "4326:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
